
spring:
  config:
    activate:
      on-profile: localn
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://happy.cwcrqv56w2zf.ap-northeast-2.rds.amazonaws.com/Instagram?serverTimezone=Asia/Seoul
    username: happy
    password: imsohappy

  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.Mysql8Dialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always